color:
  brandColors:
    - '#000000'
    - '#D9889B'
    - '#1C2F50'
    - '#FE5D58'
    - '#81616C'
  brandStrength: 0.8179206682834774
  lightness: 0.2935388311743736
  saturation: 0.6308750701136887
  rhythmicContrast: 0.7504017795436084
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: 'untethered innovation '
layout_spectrum: 0.4402486593462527
typography_spectrum: 0.9173475243151188
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FbXKvRNnXF3A%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DbXKvRNnXF3A&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FbXKvRNnXF3A%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Viral Film
          url: 'https://www.youtube.com/user/ViralFilmMedia'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - viral film
        - donnie darko
        - clip
        - jake gyllenhaal
        - official
        - exclusive media
        - time travel
        - fantasy
        - science fiction
        - scifi
        - frank
        - rabbit
      description: >-
        For all kinds of film goodness subscribe to ViralFilm:
        http://bit.ly/1oAEuMD Donnie Darko A troubled teenager is plagued by
        visions of a large bunny rabbit that manipulates him to commit a series
        of crimes, after narrowly escaping a bizarre accident. __ _ If you love
        film, You'll like this!
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=bXKvRNnXF3A&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=bXKvRNnXF3A&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=bXKvRNnXF3A&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=bXKvRNnXF3A&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=bXKvRNnXF3A&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=bXKvRNnXF3A'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=bXKvRNnXF3A
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=bXKvRNnXF3A
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=bXKvRNnXF3A'
      title: Donnie Darko - Life Line (Official Clip)
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2cbb7c52-49a0-4edf-9e02-d1ef87df23db.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2cbb7c52-49a0-4edf-9e02-d1ef87df23db.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: 'Red Pill Associates '
description: 'Cutting Edge Innovation and Insights '
github: true
